  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 text-muted" href="/index/world">g:World</a>
      <a class="p-2 text-muted" href="/index/domestic">g:U.S.</a>
      <a class="p-2 text-muted" href="/user/technology">Technology</a>
      <a class="p-2 text-muted" href="/user/design">u:Design</a>
      <a class="p-2 text-muted" href="/user/business">u:Business</a>
      <a class="p-2 text-muted" href="/admin/opinion">Opinion</a>
      <a class="p-2 text-muted" href="/admin/science">Science</a>
      <a class="p-2 text-muted" href="/admin/health">x:Health</a>
      <a class="p-2 text-muted" href="/user/index">u.Profile</a>
      <a class="p-2 text-muted" href="/admin/index">a.Users</a>
    </nav>
  </div>
    <?php echo $this->getContent(); ?>
