<div class="jumbotron p-4 p-md-5 text-secondary rounded bg-white">
    <div class="col-md-12 px-0 text-secondary">
    	<h1 class="display-4">
    		a:<?php echo $this->view->getActionName(); ?>
    	</h1>
        <p class="lead my-3">
            Page is under construction ...
        </p>
<!--         <br><br>
        <p class="lead mb-0">
            <?php echo $this->tag->linkTo(['signup', 'Sign Up', 'class' => 'btn btn-sm btn-outline-secondary']); ?>
        </p>
 -->    </div>
</div>
